In [84]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [98]:
df = pd.read_csv("clean_house_prices.csv")

In [86]:
df.head()

,Furnishing,facing,Bathroom,Balcony,Amount_numeric,BHK,Carpet_Area_sqft,Current_Floor,Total_Floors
0,Unfurnished,East,1.0,2.0,4200000.0,1.0,500.0,10.0,11.0
1,Semi-Furnished,East,2.0,2.0,9800000.0,2.0,473.0,3.0,22.0
2,Unfurnished,East,2.0,2.0,14000000.0,2.0,779.0,10.0,29.0
3,Unfurnished,East,1.0,1.0,2500000.0,1.0,530.0,1.0,3.0
4,Unfurnished,West,2.0,2.0,16000000.0,2.0,635.0,20.0,42.0

In [107]:
cat_cols = ["Furnishing", "facing"]
encoded_df = pd.get_dummies(df[cat_cols], columns=cat_cols)

In [108]:
df= pd.concat([df, encoded_df], axis=1)

In [89]:
df.head()

,Furnishing,facing,Bathroom,Balcony,Amount_numeric,BHK,Carpet_Area_sqft,Current_Floor,Total_Floors,Furnishing_Furnished,Furnishing_Semi-Furnished,Furnishing_Unfurnished,facing_East,facing_North,facing_North - East,facing_North - West,facing_South,facing_South - East,facing_South -West,facing_West
0,Unfurnished,East,1.0,2.0,4200000.0,1.0,500.0,10.0,11.0,False,False,True,True,False,False,False,False,False,False,False
1,Semi-Furnished,East,2.0,2.0,9800000.0,2.0,473.0,3.0,22.0,False,True,False,True,False,False,False,False,False,False,False
2,Unfurnished,East,2.0,2.0,14000000.0,2.0,779.0,10.0,29.0,False,False,True,True,False,False,False,False,False,False,False
3,Unfurnished,East,1.0,1.0,2500000.0,1.0,530.0,1.0,3.0,False,False,True,True,False,False,False,False,False,False,False
4,Unfurnished,West,2.0,2.0,16000000.0,2.0,635.0,20.0,42.0,False,False,True,False,False,False,False,False,False,False,True

In [109]:
df.drop(columns=["Furnishing", "facing"],inplace=True)

In [110]:
df.head()

,Bathroom,Balcony,Amount_numeric,BHK,Carpet_Area_sqft,Current_Floor,Total_Floors,Furnishing_Furnished,Furnishing_Semi-Furnished,Furnishing_Unfurnished,facing_East,facing_North,facing_North - East,facing_North - West,facing_South,facing_South - East,facing_South -West,facing_West
0,1.0,2.0,4200000.0,1.0,500.0,10.0,11.0,False,False,True,True,False,False,False,False,False,False,False
1,2.0,2.0,9800000.0,2.0,473.0,3.0,22.0,False,True,False,True,False,False,False,False,False,False,False
2,2.0,2.0,14000000.0,2.0,779.0,10.0,29.0,False,False,True,True,False,False,False,False,False,False,False
3,1.0,1.0,2500000.0,1.0,530.0,1.0,3.0,False,False,True,True,False,False,False,False,False,False,False
4,2.0,2.0,16000000.0,2.0,635.0,20.0,42.0,False,False,True,False,False,False,False,False,False,False,True

In [111]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82431 entries, 0 to 82430
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Bathroom                   82431 non-null  float64
 1   Balcony                    82431 non-null  float64
 2   Amount_numeric             82431 non-null  float64
 3   BHK                        82431 non-null  float64
 4   Carpet_Area_sqft           82431 non-null  float64
 5   Current_Floor              82431 non-null  float64
 6   Total_Floors               82431 non-null  float64
 7   Furnishing_Furnished       82431 non-null  bool
 8   Furnishing_Semi-Furnished  82431 non-null  bool
 9   Furnishing_Unfurnished     82431 non-null  bool
 10  facing_East                82431 non-null  bool
 11  facing_North               82431 non-null  bool
 12  facing_North - East        82431 non-null  bool
 13  facing_North - West        82431 non-null  bool
 14  facing_South               82431 non-null  bool
 15  facing_South - East        82431 non-null  bool
 16  facing_South -West         82431 non-null  bool
 17  facing_West                82431 non-null  bool
dtypes: bool(11), float64(7)
memory usage: 5.3 MB

In [103]:
df["Carpet_Area_sqft"].fillna(
    df["Carpet_Area_sqft"].median(),
    inplace=True
)

/tmp/ipython-input-889232604.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Carpet_Area_sqft"].fillna(

In [105]:
df['Amount_numeric'].fillna(
    df['Amount_numeric'].mean(),
    inplace=True
)

/tmp/ipython-input-1395050036.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Amount_numeric'].fillna(

In [112]:
from sklearn.model_selection import train_test_split

In [113]:
X= df.drop(columns=["Amount_numeric"])
y= df["Amount_numeric"]

In [114]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [132]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

In [133]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [134]:
model = LinearRegression()

In [135]:
model.fit(X_train, y_train)

LinearRegression()

In [130]:
y_pre=model.predict(X_test)

In [131]:
print("R2 Score:", r2_score(y_test, y_pre))
print("MAE:", mean_squared_error(y_test, y_pre))

R2 Score: 0.26318447837413095
MAE: 154877031795618.44

In [125]:
y.describe()

count    8.243100e+04
mean     1.399322e+07
std      1.540163e+07
min      2.000000e+05
25%      6.400000e+06
50%      9.000000e+06
75%      1.550000e+07
max      6.000000e+08
Name: Amount_numeric, dtype: float64

In [136]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error

lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

print("Linear Regression")
print("R2:", r2_score(y_test, y_pred_lr))
print("MAE:", mean_absolute_error(y_test, y_pred_lr))

Linear Regression
R2: 0.3933930462417532
MAE: 5690244.274157658

In [137]:
from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor(random_state=42)
dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)

print("\nDecision Tree")
print("R2:", r2_score(y_test, y_pred_dt))
print("MAE:", mean_absolute_error(y_test, y_pred_dt))

Decision Tree
R2: 0.544353230985051
MAE: 2158780.6699749213

In [138]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print("\nRandom Forest")
print("R2:", r2_score(y_test, y_pred_rf))
print("MAE:", mean_absolute_error(y_test, y_pred_rf))

Random Forest
R2: 0.7738209103379667
MAE: 1795741.8303812498

In [139]:
from sklearn.ensemble import GradientBoostingRegressor

gb = GradientBoostingRegressor(random_state=42)
gb.fit(X_train, y_train)

y_pred_gb = gb.predict(X_test)

print("\nGradient Boosting")
print("R2:", r2_score(y_test, y_pred_gb))
print("MAE:", mean_absolute_error(y_test, y_pred_gb))

Gradient Boosting
R2: 0.7265733309599935
MAE: 3532865.1409925553

In [140]:
# pip install xgboost

from xgboost import XGBRegressor

xgb = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    random_state=42
)

xgb.fit(X_train, y_train)

y_pred_xgb = xgb.predict(X_test)

print("\nXGBoost")
print("R2:", r2_score(y_test, y_pred_xgb))
print("MAE:", mean_absolute_error(y_test, y_pred_xgb))

XGBoost
R2: 0.7582470879441578
MAE: 2252805.765977214

In [141]:
results = {
    "Model": ["Linear", "Decision Tree", "Random Forest", "Gradient Boosting"],
    "R2": [
        r2_score(y_test, y_pred_lr),
        r2_score(y_test, y_pred_dt),
        r2_score(y_test, y_pred_rf),
        r2_score(y_test, y_pred_gb)
    ]
}

pd.DataFrame(results)

               Model        R2
0             Linear  0.393393
1      Decision Tree  0.544353
2      Random Forest  0.773821
3  Gradient Boosting  0.726573

In [142]:
from sklearn.ensemble import RandomForestRegressor

rf_tuned = RandomForestRegressor(
    n_estimators=500,
    max_depth=25,
    min_samples_split=5,
    min_samples_leaf=2,
    max_features="sqrt",
    random_state=42,
    n_jobs=-1
)

rf_tuned.fit(X_train, y_train)
y_pred = rf_tuned.predict(X_test)

from sklearn.metrics import r2_score
print("R2:", r2_score(y_test, y_pred))

R2: 0.80190354463097

In [143]:
from xgboost import XGBRegressor

xgb = XGBRegressor(
    n_estimators=800,
    learning_rate=0.05,
    max_depth=8,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

xgb.fit(X_train, y_train)
y_pred = xgb.predict(X_test)

print("R2:", r2_score(y_test, y_pred))

R2: 0.7634827368910451

In [144]:
import joblib

joblib.dump(rf_tuned, "random_forest_model.pkl")

['random_forest_model.pkl']

In [145]:
joblib.dump(scaler, "scaler.pkl")

['scaler.pkl']